---
- name: How to prompt for varibles
  hosts: localhost
  gather_facts: no

  vars_prompt:
          - name: "yourpasswordvar" ##var to define
            prompt: "What is your password?" ## question to ask
            private: yes ##does not echo your password
            encrypt: "sha512_crypt"
            confirm: yes


  tasks: 
  - name: show the results
    debug:
            var: yourpasswordvar
